name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    # Do not ignore bash profile files. From:
    defaults:
      run:
        shell: bash -l {0}
        
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - run: echo $PATH
    - name: Set up toolchain
      run: echo "/scratch/tk/chipyard/.conda-env/riscv-tools/bin/" >> $GITHUB_PATH
    - run: echo $PATH
    - run: make
